name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run pylint, fail if score is below 7.5
    - name: Analysing the code with pylint, ignore j2l
      run: |
        pylint $(git ls-files '*.py') --ignore-path=src/api/j2l/* 
        pylint_score=$?
        if [ $pylint_score -lt 75 ]; then
          echo "Pylint score is below 7.5"
          exit 1
        fi
    - name: Running unittests
      run: |
        python -m unittest
