name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip coverage pylint
        pip install -r requirements.txt

    # Run pylint, fail if score is below 7.5, --ignore-path=src/api/j2l/* to ignore j2l
    - name: Analysing the code with pylint, ignore j2l
      run: |
        pylint --fail-under=7.5 --ignore-path=src/api/j2l/* src

    # Run unittests with coverage, fail if coverage is below 80%, fail if more than 10% tests fail
    # if no coverage data is generated, the build will fail
    - name: Running unittests
      run: |
        python -m coverage run -m unittest discover -s tests
        python -m coverage report -m --fail-under=80 --omit=tests/*,src/api/j2l/*
