name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pylint

    # Run pylint, fail if score is below 7.5, --ignore-path=src/api/j2l/* to ignore j2l
    # ignore  W1203: Use % formatting in logging functions and pass the % parameters as arguments
    - name: Analysing the code with pylint, ignore j2l
      run: |
        pylint --fail-under=7.5 --ignore-path=src/api/j2l/* --disable=W1203 src tests 

